##############################################################################################
# Incluir aqui las propiedades a utilizar por Spring Boot y los componentes de la aplicación #
##############################################################################################
# ===================================================================
# Spring Boot configuration.
# ===================================================================
spring:
  application:
    name: clp-bck-<%=resource%>-q
    environment: LOCAL
  jackson:
    default-property-inclusion: non_null
  data:
    mongodb:
      host: localhost
      port: 27017
      database: MUR
      uri: mongodb://localhost:27017

# ===================================================================
# Tracing configuration.
# ===================================================================
  sleuth:
    reactor:
      instrumentation-type: decorate_queues
    baggage:
     correlation-enabled: true
     remote-fields:
       - x-correlationid
     correlation-fields:
       - x-correlationid

mongodb:
  write-concern:
    w: 1
    j: false
    wtimeout: 20
# ===================================================================
# TLS Configuration.
# ===================================================================
#  tls:
#    caFile: /path/to/ca.crt #Certificate of the certifying authority (CA)
#    certificateKeyFile:  /path/to/mongodb.pem #Mongo server key (pem)
#    enabled: true #To enable TLS connection with Mongodb

debug: false

# LOCAL WES SYMETRIC
access-token-processor:
  signature:
    algorithm: HS512
    type: SYMMETRIC_KEY
    symmetric:
      secretKey: tV0mAkhX6UQd94JaResG
  claims:
    audience: wes-idp
    optionalValidation:
      clientId: false
      jwtId: false
      scope: false
  type: WES_BME
  verifySignature: true

roles: ReadOnly-sup

jwt:
  algorithm: HS512

# ===================================================================
# Application specific properties
# ===================================================================
use:
 jpa: false
 mongo: true

# ===================================================================
# Application monitoring properties
# ===================================================================
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: prometheus,info,health,metrics,mappings,refresh
    enabled-by-default: false

  endpoint:
    prometheus:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
    metrics:
      enabled: true
    mappings:
      enabled: true
    refresh:
      enabled: true

# ===================================================================
# Logging
# ===================================================================
logging:
  level:
    org.springframework.web: ERROR 

# ===================================================================
# Logback default properties
# ===================================================================
info:
  name: DCleaR
  classification: C1
  application: A0928
  component: A0928.4
  product: DCleaR
  vendor: SIX
  version: 1

# ===================================================================
# Patterns/JSON:API
# ===================================================================
pagination:
  defaultPageNumber: 0
  defaultPageSize: 20
  defaultSortField: +attributeId